# Generated by Django 5.2.6 on 2025-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSubmition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('has_allergies', models.BooleanField(default=False, null=True)),
                ('has_medical_conditions', models.BooleanField(blank=True, default=False, null=True)),
                ('recent_major_health_event', models.BooleanField(blank=True, default=False, null=True)),
                ('taking_meds_or_supplements', models.BooleanField(blank=True, default=False, null=True)),
                ('sensitive_skin_or_dermatitis', models.BooleanField(blank=True, default=False, null=True)),
                ('pregnancy_status', models.CharField(choices=[('pregnant', 'Pregnant'), ('breastfeeding', 'Breasting Feeding'), ('trying to conceive', 'Trying To Conceive'), ('none', 'None of the Above')], default='none', max_length=50)),
                ('self_care_goals', models.CharField(blank=True, choices=[('relax_stress', 'Relaxation & Stress Relief'), ('better_sleep', 'Better Sleep'), ('skincare', 'Skincare & Nourishment'), ('energy_focus', 'More Energy / Focus'), ('emotional_balance', 'Emotional Balance'), ('other', 'Other')], max_length=50)),
                ('self_care_goals_other', models.CharField(blank=True, help_text='If other, please specify.', max_length=200)),
                ('product_interests', models.CharField(blank=True, choices=[('herbal_beverages', 'Herbal Beverages'), ('facial_care', 'Facial Care'), ('oral_care', 'Oral Care'), ('body_care', 'Body Care'), ('open_to_anything', 'Open to Anything')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('consent_understand_not_medical', models.BooleanField(blank=True, null=True)),
                ('consent_review_answers', models.BooleanField(blank=True, null=True)),
                ('consent_read_safety_info', models.BooleanField(blank=True, null=True)),
                ('consent_use_products_safely', models.BooleanField(blank=True, null=True)),
                ('raw_post', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
