# Generated by Django 5.2.6 on 2025-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsubmition',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
