# Generated by Django 5.2.6 on 2025-11-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationsubmition_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsubmition',
            name='middle_name',
        ),
    ]
