# Generated by Django 5.2.6 on 2025-11-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_consultationsubmition_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsubmition',
            name='pregnancy_status',
            field=models.CharField(choices=[('pregnant', 'Pregnant'), ('breastfeeding', 'Breast Feeding'), ('trying to conceive', 'Trying To Conceive'), ('none', 'None of the Above')], default='none', max_length=50),
        ),
    ]
