# Generated by Django 5.2.6 on 2025-11-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_consultationsubmition_pregnancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsubmition',
            name='has_allergies_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationsubmition',
            name='has_medical_conditions_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationsubmition',
            name='recent_major_health_event_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationsubmition',
            name='taking_meds_or_supplements_details',
            field=models.TextField(blank=True),
        ),
    ]
