# Generated by Django 5.2.6 on 2025-11-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultationsubmition_has_allergies_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsubmition',
            name='sensitive_skin_or_dermatitis_details',
            field=models.TextField(blank=True),
        ),
    ]
