# Generated by Django 5.2.6 on 2025-11-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultationsubmition_sensitive_skin_or_dermatitis_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationSubmition',
            new_name='ConsultationSubmission',
        ),
    ]
